
language: java

jdk:
  - oraclejdk9
  - openjdk8

branches:
  only:
    - master
    - jdk9

script: "./gradlew check test --info --continue"

after_success:
    - ./gradlew jacocoTestReport coveralls --info

